[wip] add mesh simplification to onshape exporter library
kscalelabs/onshape pull request #20
Opened 2024-06-01 01:50 UTC by codekansas

2024-06-06 07:59 UTC, codekansas commented on kol/onshape/converter.py
> +            print(connected_parts)
@wuallenwu plz avoid print statements

2024-06-08 14:50 UTC, hu-po approved these changes
send it :rocket:

2024-06-11 16:21 UTC, wuallenwu commented
Current action items

1. Get mesh simplification working - specifically there's an off by one error when trying to run the current script on the random.stl in the repo. (high prio)
2. Support for all link and joint types in the stompy urdf (high prio, probably very involved)
3. Script to simplify all collision meshes in a urdf (low prio, should be pretty easy)
4. Finish adding combining two inertial rpy, test merge_fixed_joints on a bigger urdf
5. Add all the scripts to the autoupload pipeline.

2024-06-11 16:38 UTC, hu-po commented on kol/requirements.txt
maybe worth pinning these requirement versions?

2024-06-11 16:39 UTC, hu-po commented on kol/merge_fixed_joints.py
I like the typing, this code is complex so its definitely a good idea

2024-06-11 16:42 UTC, hu-po commented on kol/scripts/cli.py
we should add sections in the README that tell the user example commands they can run. it should be easy for someone without deep knowledge to just scroll through the readme and copy paste the one command they need.

2024-06-11 16:46 UTC, hu-po commented
@wuallenwu overall I feel like this is a good direction to take this repo. Adding types and tests and just generally cleaning it up while you add the specific requested features (afaik simplification and merging?). But tbh its just too much for me to really dig deep and understand what is going on, let alone know how to fix specific bugs.

2024-06-11 17:20 UTC, budzianowski requested changes
See first clean up nits. This PR is already way to big so given all the upcoming action items, you should stop adding things but polish existing version and add more tests.

Every new points from the list should be another PR.

2024-06-11 17:20 UTC, budzianowski commented on kol/merge_fixed_joints.py
> +    # Get initial rpy of parent and child
Remove if not used

2024-06-11 17:20 UTC, budzianowski commented on kol/simplify_old/utils.py
> +"""Defines mesh simplification utility functions."""
remove the whole folder?

2024-06-12 01:56 UTC, merged